In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("../data/raw/student-mat.csv", sep=";")

df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [5]:
def categorize_performance(grade):
    if grade < 10:
        return "At Risk"
    elif grade < 15:
        return "Average"
    else:
        return "High Performance"


df["performance_category"] = df["G3"].apply(categorize_performance)

df[["G3", "performance_category"]].head(10)

   G3 performance_category
0   6              At Risk
1   6              At Risk
2  10              Average
3  15     High Performance
4  10              Average
5  15     High Performance
6  11              Average
7   6              At Risk
8  19     High Performance
9  15     High Performance

In [6]:
def categorize_performance(grade):
    if grade < 10:
        return "At Risk"
    elif grade < 15:
        return "Average"
    else:
        return "High Performance"


df["performance_category"] = df["G3"].apply(categorize_performance)

In [7]:
excluded_columns = [
    "G1",
    "G2",
    "G3",
    "performance_category"
]

X = df.drop(columns=excluded_columns)

y = df["performance_category"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (395, 30)
y shape: (395,)

In [8]:
categorical_columns = X.select_dtypes(
    include=["object", "str"]
).columns.tolist()

numerical_columns = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

print("Categorical columns:", categorical_columns)
print("Numerical columns:", numerical_columns)

Categorical columns: ['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic']
Numerical columns: ['age', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences']

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)

print("\nTraining target:")
print(y_train.value_counts())

print("\nTesting target:")
print(y_test.value_counts())

Training features: (316, 30)
Testing features: (79, 30)

Training target:
performance_category
Average             154
At Risk             104
High Performance     58
Name: count, dtype: int64

Testing target:
performance_category
Average             38
At Risk             26
High Performance    15
Name: count, dtype: int64

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline

In [11]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_columns
        ),
        (
            "numerical",
            StandardScaler(),
            numerical_columns
        )
    ]
)

In [12]:
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

print("Processed training shape:", X_train_processed.shape)
print("Processed testing shape:", X_test_processed.shape)

Processed training shape: (316, 56)
Processed testing shape: (79, 56)

In [13]:
print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)

Training features: (316, 30)
Testing features: (79, 30)

In [14]:
print(y_train.value_counts())
print(y_test.value_counts())

performance_category
Average             154
At Risk             104
High Performance     58
Name: count, dtype: int64
performance_category
Average             38
At Risk             26
High Performance    15
Name: count, dtype: int64

In [15]:
print("Processed training shape:", X_train_processed.shape)
print("Processed testing shape:", X_test_processed.shape)

Processed training shape: (316, 56)
Processed testing shape: (79, 56)